// <auto-generated />
using System;
using KipCart.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KipCart.Database.Migrations
{
    [DbContext(typeof(KipCartContext))]
    partial class KipCartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KipCart.Database.Entities.Good", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsShow")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("KipCart.Database.Entities.Purchase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("KipCart.Database.Entities.PurchaseGood", b =>
                {
                    b.Property<int>("PurchaseID")
                        .HasColumnType("int");

                    b.Property<int>("GoodID")
                        .HasColumnType("int");

                    b.Property<uint>("GoodAmount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GoodPrice")
                        .HasColumnType("int unsigned");

                    b.HasKey("PurchaseID", "GoodID");

                    b.HasIndex("GoodID");

                    b.ToTable("PurchasesGoods");
                });

            modelBuilder.Entity("KipCart.Database.Entities.PurchaseGood", b =>
                {
                    b.HasOne("KipCart.Database.Entities.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KipCart.Database.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseGoods")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("KipCart.Database.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
